In [6]:
import pandas as pd
import numpy as np
import os

In [9]:
0

0

In [7]:
import os
import pandas as pd

# Construct the file path using os.path.join
desktop_path = os.path.join(os.path.expanduser("~"), "Desktop")
file_path = os.path.join(desktop_path, "data", "sample_prices.csv")

# Read the CSV file into a DataFrame
prices = pd.read_csv(file_path)

In [12]:
returns = prices.pct_change()
returns

        BLUE    ORANGE
0        NaN       NaN
1   0.023621  0.039662
2  -0.021807 -0.033638
3  -0.031763  0.082232
4   0.034477  0.044544
5   0.037786 -0.026381
6  -0.011452 -0.049187
7   0.032676  0.117008
8  -0.012581  0.067353
9   0.029581  0.078249
10  0.006151 -0.168261
11  0.012162  0.024041
12  0.021149 -0.055623

In [14]:
returns = returns.dropna()

In [15]:
returns.std()

BLUE      0.023977
ORANGE    0.079601
dtype: float64

In [16]:
"construct the analytical os std"

'construct the analytical os std'

In [28]:
deviations = returns - returns.mean()
squared_dev = deviations**2
summation = squared_dev.sum()
variance = summation/(len(returns['BLUE'])-1)
variance1 = squared_dev.mean()

In [29]:
stand_dev = np.sqrt(variance)
stand_dev

BLUE      0.023977
ORANGE    0.079601
dtype: float64

In [32]:
'annualize volatility'
stand_dev_an = np.sqrt(12) * stand_dev

In [33]:
stand_dev_an

BLUE      0.083060
ORANGE    0.275747
dtype: float64

In [8]:
# Construct the file path using os.path.join
desktop_path = os.path.join(os.path.expanduser("~"), "Desktop")
file_path = os.path.join(desktop_path, "data", "Portfolios_Formed_on_ME_monthly_EW.csv")

# Read the CSV file into a DataFrame
prices = pd.read_csv(file_path , header=0 , index_col=0 , parse_dates =True , na_values=-99.99)

In [9]:
prices.head()

,<= 0,Lo 30,Med 40,Hi 30,Lo 20,Qnt 2,Qnt 3,Qnt 4,Hi 20,Lo 10,Dec 2,Dec 3,Dec 4,Dec 5,Dec 6,Dec 7,Dec 8,Dec 9,Hi 10
192607,NaN,-0.43,1.52,2.68,-0.57,0.59,1.60,1.47,3.33,-1.45,0.29,-0.15,1.33,1.24,1.98,1.55,1.38,3.38,3.29
192608,NaN,3.90,3.04,2.09,3.84,3.59,3.71,1.61,2.33,5.12,2.59,4.03,3.15,2.72,4.72,1.60,1.63,0.98,3.70
192609,NaN,-1.08,-0.54,0.16,-0.48,-1.40,0.00,-0.50,-0.09,0.93,-1.87,-2.27,-0.53,0.07,-0.07,-1.64,0.64,-0.86,0.67
192610,NaN,-3.32,-3.52,-3.06,-3.29,-4.10,-2.89,-3.36,-2.95,-4.84,-1.77,-3.36,-4.83,-2.98,-2.80,-3.45,-3.27,-3.47,-2.43
192611,NaN,-0.46,3.82,3.09,-0.55,2.18,3.41,3.39,3.16,-0.78,-0.32,-0.29,4.65,3.24,3.57,3.82,2.95,3.61,2.70

In [10]:
returns = prices
columns = ['Lo 10', 'Hi 10']
returns = returns[columns]
returns = returns/100
returns.head()

         Lo 10   Hi 10
192607 -0.0145  0.0329
192608  0.0512  0.0370
192609  0.0093  0.0067
192610 -0.0484 -0.0243
192611 -0.0078  0.0270

In [11]:
volatility= returns.std()
volatility

Lo 10    0.106288
Hi 10    0.053900
dtype: float64

In [12]:
annualized_vol = volatility*np.sqrt(12)
annualized_vol

Lo 10    0.368193
Hi 10    0.186716
dtype: float64

In [15]:
n_months = returns.shape[0]
return_per_month = ((returns+1).prod()**(1/n_months)) - 1
return_per_month

Lo 10    0.012986
Hi 10    0.007423
dtype: float64

In [18]:
annualized_ret = ((return_per_month+1)**12) -1

In [19]:
annualized_ret

Lo 10    0.167463
Hi 10    0.092810
dtype: float64

In [21]:
ret_risk_ratio = annualized_ret/annualized_vol
riskfree = 0.03
an_excess_ret= annualized_ret - riskfree
print(ret_risk_ratio)
sharpe_ratio = an_excess_ret/annualized_vol
sharpe_ratio

Lo 10    0.454825
Hi 10    0.497063
dtype: float64

Lo 10    0.373346
Hi 10    0.336392
dtype: float64